import { TypeEntretien } from '@shared/enums/type-entretien.enum';
import { AppreciationGeneraleEnum } from '@shared/enums/appreciation_generale.enum';
import { Personne } from './personne.model';
import { StatutDemandeEnum } from '@shared/enums/statut.demande.enum';
import { FormationsDispensees } from './formations-dispensees.model';
import { FormationsRealisees } from './formations-realisees.model';
import { FormationsDemandees } from './formations-demandees.model';
import { FormationsContinue } from './formations-continue.model';
import { ActionsFormationsDemandees } from './ actions-formations-demandees.model';

export interface Entretien {
  id: number;
  type: TypeEntretien;
  statut: StatutDemandeEnum;
  dateEntretien: string;
  structure: string;
  intitulePoste: string;
  dateAffectation: string | null;
  emploiType: string;
  positionPoste: string;
  quotiteAffectation: string;
  missions: string;
  conduiteProjet: boolean;
  encadrement: boolean;
  cpeNbAgent: number;
  cpeCategA: number;
  cpeCategB: number;
  cpeCategC: number;
  rappelObjectifs: string;
  evenementsSurvenus: string;
  caCompetences: string;
  caContribution: string;
  caCapacites: string;
  caAptitude: string;
  agCompetences: AppreciationGeneraleEnum;
  agContribution: AppreciationGeneraleEnum;
  agCapacites: AppreciationGeneraleEnum;
  agAptitude: AppreciationGeneraleEnum;
  realisationObjectifs: string;
  appreciationLitterale: string;
  acquisExperiencePro: string;
  objectifsActivites: string;
  demarcheEnvisagee: string;
  evolutionActivites: string;
  evolutionCarriere: string;
  personne: Personne;
  superieur?: Personne;
  dateTransmission?: string;
  commentairesEvaluation?: string;
  commentairesEvaluationPerspectives?: string;
  dateEntretienPrecedent?: string | null;
  soldeCPF: number;
  utiliserCPF: number;
  formationsDispensees?: FormationsDispensees[];
  formationsRealisees?: FormationsRealisees[];
  formationsDemandees?: FormationsDemandees[];
  formationsContinue?: FormationsContinue[];
  actionsFormationsDemandees?: ActionsFormationsDemandees[];
  formationsPreparationConcours?: string;
  formationsConstruireProjet?: string;
}
