import { TypeEntretien } from '@shared/enums/type-entretien.enum';
import { AppreciationGeneraleEnum } from '@shared/enums/appreciation_generale.enum';
import { Personne } from './personne.model';
import { StatutDemandeEnum } from '@shared/enums/statut.demande.enum';

export interface Entretien {
  id: number;
  type: TypeEntretien;
  statut: StatutDemandeEnum;
  dateEntretien: string;
  structure: string;
  intitulePoste: string;
  dateAffectation: string | null;
  emploiType: string;
  positionPoste: string;
  quotiteAffectation: string;
  missions: string;
  conduiteProjet: boolean;
  encadrement: boolean;
  cpeNbAgent: number;
  cpeCategA: number;
  cpeCategB: number;
  cpeCategC: number;
  rappelObjectifs: string;
  evenementsSurvenus: string;
  caCompetences: string;
  caContribution: string;
  caCapacites: string;
  caAptitude: string;
  agCompetences: AppreciationGeneraleEnum;
  agContribution: AppreciationGeneraleEnum;
  agCapacites: AppreciationGeneraleEnum;
  agAptitude: AppreciationGeneraleEnum;
  realisationObjectifs: string;
  appreciationLitterale: string;
  acquisExperiencePro: string;
  objectifsActivites: string;
  demarcheEnvisagee: string;
  evolutionActivites: string;
  evolutionCarriere: string;
  personne: Personne;
  superieur?: Personne;
  dateTransmission?: string;
  commentairesEvaluation?: string;
  commentairesEvaluationPerspectives?: string;
}
